name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: cache/requirements.txt
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py
      - name: Commit and push changes
        run: |-
          git config --global user.email "github-actions-bot@andrewkillion.github.io"
          git config --global user.name "AndrewKillion/GitHub-Actions-Bot"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated README"
            git pull --rebase
            git push
          fi
